# Minimal test blueprint (web service only)
services:
  - type: web
    name: flask-backend
    branch: David-Jones
    env: python
    plan: starter
    buildCommand: echo "no-op"
    startCommand: echo "started"

