# Free blueprint — no persistent disk (SQLite ephemeral)
services:
  - type: web
    runtime: python
    name: flask-backend
    branch: David-Jones
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT

  - type: web
    runtime: static
    name: react-frontend
    branch: David-Jones
    plan: free
    buildCommand: npm install && npm run build
    staticPublishPath: dist
