# Render Blueprint (render.yaml) – Flask + React + SQLite with persistent disk
services:
  - type: web
    runtime: python
    name: flask-backend
    branch: David-Jones
    plan: starter
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT
    disks:
      - name: sqlite-disk
        mountPath: /var/data
    envVars:
      - key: SQLITE_PATH
        value: /var/data/app.db

  - type: web
    runtime: static
    name: react-frontend
    branch: David-Jones
    plan: free
    buildCommand: npm install && npm run build
    staticPublishPath: dist

disks:
  - name: sqlite-disk
    sizeGb: 1
    plan: standard
